[INFO   ] Logger: Record log in /storage/emulated/0/Download/AlgoMedApp/.kivy/logs/kivy_25-07-20_0.txt
[DEBUG  ] Config: Upgrading from 0 to 1
[WARNING] Config: Upgrading configuration in progress.
[WARNING] Config: Older configuration version detected (0 instead of 27)
[INFO   ] Kivy: v2.3.1
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.13.2 (main, Mar 31 2025, 08:14:59) [GCC 11.4.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[INFO   ] Logger: Purge log fired. Processing...
[INFO   ] Logger: Purge finished!
[INFO   ] Factory: 195 symbols loaded
[INFO   ] KivyMD: 1.2.0, git-Unknown, 2025-06-07 (installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivymd/__init__.py")
[WARNING] KivyMD: Version 1.2.0 is deprecated and is no longer supported. Use KivyMD version 2.0.0 from the master branch (pip install https://github.com/kivymd/KivyMD/archive/master.zip)
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.2 V@0530.55.1 (GIT@9ad1b67875, Ib48d2dada6, 1746950435) (Date:05/11/25)'>
[INFO   ] GL: OpenGL vendor <b'Qualcomm'>
[INFO   ] GL: OpenGL renderer <b'Adreno (TM) 660'>
[INFO   ] GL: OpenGL parsed version: 3, 2
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/Download/AlgoMedApp/main.py", line 39, in <module>
[WARNING] stderr:     WebViewApp().run()
[WARNING] stderr:     ~~~~~~~~~~~~~~~~^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/app.py", line 955, in run
[WARNING] stderr:     self._run_prepare()
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/app.py", line 925, in _run_prepare
[WARNING] stderr:     root = self.build()
[WARNING] stderr:   File "/storage/emulated/0/Download/AlgoMedApp/main.py", line 19, in build
[WARNING] stderr:     request_permissions([Permission.INTERNET, Permission.READ_EXTERNAL_STORAGE])
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/android/permissions.py", line 598, in request_permissions
[WARNING] stderr:     _RequestPermissionsManager.request_permissions(permissions, callback)
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/android/permissions.py", line 538, in request_permissions
[WARNING] stderr:     cls.register_callback()
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~~~~~^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/android/permissions.py", line 514, in register_callback
[WARNING] stderr:     cls._java_callback = _onRequestPermissionsCallback(cls.python_callback)
[WARNING] stderr:                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/android/permissions.py", line 467, in __init__
[WARNING] stderr:     super().__init__()
[WARNING] stderr:     ~~~~~~~~~~~~~~~~^^
[WARNING] stderr:   File "jnius/jnius_proxy.pxi", line 28, in jnius.jnius.PythonJavaClass.__init__
[WARNING] stderr:   File "jnius/jnius_proxy.pxi", line 34, in jnius.jnius.PythonJavaClass._init_j_self_ptr
[WARNING] stderr:   File "jnius/jnius_proxy.pxi", line 180, in jnius.jnius.create_proxy_instance
[WARNING] stderr:   File "jnius/jnius_export_class.pxi", line 876, in jnius.jnius.JavaMethod.__call__
[WARNING] stderr:   File "jnius/jnius_export_class.pxi", line 1042, in jnius.jnius.JavaMethod.call_staticmethod
[WARNING] stderr:   File "jnius/jnius_utils.pxi", line 79, in jnius.jnius.check_exception
[WARNING] stderr: jnius.jnius.JavaException: JVM exception occurred: interface org.kivy.android.PythonActivity$PermissionsCallback is not visible from class loader java.lang.IllegalArgumentException
